name: Publish an image in DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_pass }}
