name: Publish an image in DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4